# Host: localhost  (Version 8.0.30)
# Date: 2025-03-19 05:50:06
# Generator: MySQL-Front 6.0  (Build 2.20)


#
# Structure for table "agenda"
#

CREATE TABLE `agenda` (
  `EVENTO_ID` int NOT NULL AUTO_INCREMENT,
  `EVENTO_CLIENTE_ID` varchar(255) NOT NULL DEFAULT '0',
  `EVENTO_SERVICOS` varchar(255) DEFAULT '0',
  `EVENTO_DATA` date DEFAULT NULL,
  `EVENTO_HORA` time DEFAULT '00:00:00',
  `EVENTO_STATUS` enum('PENDENTE','CONFIRMADO','CANCELADO') NOT NULL DEFAULT 'PENDENTE',
  `EVENTO_RESPONSAVEL` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`EVENTO_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

#
# Data for table "agenda"
#

INSERT INTO `agenda` VALUES (6,'4','CORTE,  SPA, TINTURA','2025-03-19','10:00:00','CANCELADO',1);

#
# Structure for table "clientes"
#

CREATE TABLE `clientes` (
  `CLIENTE_ID` int NOT NULL AUTO_INCREMENT,
  `CLIENTE_NOME` varchar(255) DEFAULT NULL,
  `CLIENTE_NASCIMENTO` date DEFAULT NULL,
  `CLIENTE_SEXO` enum('MASCULINO','FEMININO') DEFAULT NULL,
  `CLIENTE_LOGRADOURO` varchar(255) DEFAULT NULL,
  `CLIENTE_NUMERO` varchar(255) DEFAULT NULL,
  `CLIENTE_COMPLEMENTO` varchar(255) DEFAULT NULL,
  `CLIENTE_BAIRRO` varchar(255) DEFAULT NULL,
  `CLIENTE_CIDADE` varchar(255) DEFAULT NULL,
  `CLIENTE_UF` varchar(255) DEFAULT NULL,
  `CLIENTE_CEP` varchar(255) NOT NULL DEFAULT '00000-000',
  `CLIENTE_TELEFONE` varchar(255) DEFAULT NULL,
  `CLIENTE_CELULAR` varchar(255) DEFAULT NULL,
  `CLIENTE_EMAIL` varchar(255) DEFAULT NULL,
  `CLIENTE_SENHA` varchar(255) DEFAULT NULL,
  `CLIENTE_ATIVO` enum('S','N') DEFAULT 'S',
  `DATA_CADASTRO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DATA_ALTERACAO` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `AUTOR_ALTERACAO` int NOT NULL DEFAULT '0',
  `DATA_EXCLUSAO` datetime DEFAULT NULL,
  `AUTOR_EXCLUSAO` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`CLIENTE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

#
# Data for table "clientes"
#

INSERT INTO `clientes` VALUES (4,'José Roberto Dourado Junior','1992-10-23','MASCULINO','Rua Abs Yasbek','162','Bl 15 Ap 402','Vila Maria','Marília','SP','17527-560','(14) 3434-3434','(14) 99869-0192','diisantorsula@gmail.com','e8d95a51f3af4a3b134bf6bb680a213a','S','2025-03-19 05:20:28','2025-03-19 05:20:48',0,NULL,0);

#
# Structure for table "colaboradores"
#

CREATE TABLE `colaboradores` (
  `COLAB_ID` int NOT NULL AUTO_INCREMENT,
  `COLAB_NOME` varchar(255) DEFAULT NULL,
  `COLAB_NASCIMENTO` date DEFAULT NULL,
  `COLAB_SEXO` enum('MASCULINO','FEMININO') NOT NULL DEFAULT 'MASCULINO',
  `COLAB_LOGRADOURO` varchar(255) DEFAULT NULL,
  `COLAB_NUMERO` varchar(255) DEFAULT NULL,
  `COLAB_COMPLEMENTO` varchar(255) DEFAULT NULL,
  `COLAB_BAIRRO` varchar(255) DEFAULT NULL,
  `COLAB_UF` varchar(255) DEFAULT NULL,
  `COLAB_CIDADE` varchar(255) DEFAULT NULL,
  `COLAB_CEP` varchar(255) DEFAULT NULL,
  `COLAB_TELEFONE` varchar(255) DEFAULT NULL,
  `COLAB_CELULAR` varchar(255) DEFAULT NULL,
  `COLAB_EMAIL` varchar(255) DEFAULT NULL,
  `COLAB_SENHA` varchar(255) DEFAULT NULL,
  `COLAB_ATIVO` enum('S','N') DEFAULT NULL,
  `COLAB_PERMISSAO` enum('ADMIN','GERENCIA','USUARIO') DEFAULT 'USUARIO',
  PRIMARY KEY (`COLAB_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

#
# Data for table "colaboradores"
#

INSERT INTO `colaboradores` VALUES (1,'Leila','1990-01-02','MASCULINO','','','','',NULL,'','','','','leila@leila.com.br','754f9968bf5f5f68d7dea029889b7415','S','ADMIN');
